spring.application.name=usetiming

spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/{tenent-id}/v2.0
spring.security.oauth2.client.registration.azure-dev.provider=azure
spring.security.oauth2.client.registration.azure-dev.client-id={client-id}
spring.security.oauth2.client.registration.azure-dev.client-secret={client-secret}
spring.security.oauth2.client.registration.azure-dev.scope=openid, email, profile, User.Read, User.ReadBasic.All

#API
app.config.graphAPIUrl = https://graph.microsoft.com/v1.0
app.config.appRegistrationId = azure-dev
