spring.application.name=usetiming

spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/24839cd3-4f27-4b00-8bef-b471a198098c/v2.0
spring.security.oauth2.client.registration.azure-dev.provider=azure
spring.security.oauth2.client.registration.azure-dev.client-id=35437750-da5e-41a3-86f9-9e1709fa1a1e
spring.security.oauth2.client.registration.azure-dev.client-secret=3S~8Q~R9zHuRtvsWMT2emxUR7Gx1RxhyZgluuaTy
spring.security.oauth2.client.registration.azure-dev.scope=openid, email, profile, User.Read, User.ReadBasic.All

#API
microsoftGraphApi.baseUrl = https://graph.microsoft.com/v1.0
